db.host=localhost
db.port=3306
db.name=factura_email
db.user=root
db.password=ALTERAR

email.remetente=seuemail@gmail.com
email.senhaApp=ALTERAR
email.assunto=Envio de documento
email.smtpHost=smtp.gmail.com
email.smtpPort=465
